name: Publish Any Commit
on: [push, pull_request]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Publish packages
        run: npx pkg-pr-new publish --json output.json --comment=off

      - name: Post or update comment
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs');
            const output = JSON.parse(fs.readFileSync('output.json', 'utf8'));

            const packages = output.packages.map(p => `- ${p.name}: ${p.url}`).join('\n');
            const templates = output.templates.map(t => `- [${t.name}](${t.url})`).join('\n');

            const body = `## Custom Publish Message for ${context.sha.substring(0, 7)}

            ### Published Packages:

            ${packages}

            ### Templates:

            ${templates}`;

            const botCommentIdentifier = '## Custom Publish Message';

            async function findBotComment() {
              const comments = await github.rest.issues.listComments({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number
              });
              return comments.data.find(comment => comment.body.includes(botCommentIdentifier));
            }

            if (context.eventName === 'pull_request') {
              const existingComment = await findBotComment();
              if (existingComment) {
                await github.rest.issues.updateComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  comment_id: existingComment.id,
                  body: body
                });
              } else {
                await github.rest.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: body
                });
              }
            } else if (context.eventName === 'push') {
              const pullRequests = await github.rest.pulls.list({
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'open',
                head: `${context.repo.owner}:${context.ref.replace('refs/heads/', '')}`
              });
              
              if (pullRequests.data.length > 0) {
                const pr = pullRequests.data[0];
                const existingComment = await findBotComment();
                if (existingComment) {
                  await github.rest.issues.updateComment({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    comment_id: existingComment.id,
                    body: body
                  });
                } else {
                  await github.rest.issues.createComment({
                    issue_number: pr.number,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    body: body
                  });
                }
              } else {
                console.log('No open pull request found for this push. Cannot post comment.');
              }
            }
