name: Publish Any Commit
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Publish packages
        run: npx pkg-pr-new publish --json output.json --comment=off

      - name: Post custom comment
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          output=$(cat output.json)
          packages=$(echo "$output" | jq -r '.packages[] | "- \(.name): \(.url)"' | sed -z 's/\n/\\n/g')
          templates=$(echo "$output" | jq -r '.templates[] | "- [\(.name)](\(.url))"' | sed -z 's/\n/\\n/g')
          body="## Custom Publish Message\n\n### Published Packages:\n\n$packages\n\n### Templates:\n\n$templates"

          pr_number=${{ github.event.pull_request.number }}
          repo_full_name=${{ github.repository }}

          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$repo_full_name/issues/$pr_number/comments \
            -d "{\"body\":\"$body\"}"
